services:
  - type: static
    name: gradebase-app
    buildCommand: npm ci && npm run build -- --output-path=dist/gradebase-app
    publishPath: dist/gradebase-app
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
