services:
  - type: static
    name: gradebase-app-front
    env: static
    branch: master
    buildCommand: npm ci && npm run build -- --output-path=dist/gradebase-app
    publishDir: dist/gradebase-app
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
